# Generated by Django 3.1.1 on 2020-09-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(unique=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
