# Generated by Django 3.1.1 on 2020-09-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100, unique=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
