# Generated by Django 3.1.1 on 2020-09-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='text',
            new_name='word',
        ),
    ]
